disabled_rules: # rule identifiers to exclude from running
- multiple_closures_with_trailing_closure
- legacy_constructor
- empty_parentheses_with_trailing_closure
- nesting
- function_parameter_count
- line_length
- function_body_length
- shorthand_operator
- trailing_newline
- identifier_name
- type_name
- trailing_whitespace

opt_in_rules: # some rules are only opt-in
- control_statement
- colon
- comma
- identifier_name

included: # paths to include during linting. `--path` is ignored if present.
- weather
- weatherTests
- weatherUITests
excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods
- weather/R.generated.swift

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly. Give warning only for force casting

force_try:
severity: warning # explicitly. Give warning only for force try

type_body_length:
- 500 # warning
- 800 # error

# or they can set both explicitly
file_length:
warning: 800
error: 1000

large_tuple: # warn user when using 3 values in tuple, give error if there are 4
- 3
- 4

line_length:
ignores_comments: true
warning: 150

#cyclomatic_complexity: #Cyclomatic Complexity Violation: Function should have complexity 10 or less
#warning: 15
#error: 30

cyclomatic_complexity: 22

# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
min_length: 4 # only warning
max_length: # warning and error
warning: 30
error: 40
excluded: iPhone # excluded via string

identifier_name:
allowed_symbols: "_"
min_length: # only min_length
warning: 3 # only warning
max_length:
warning: 90
error: 1000
excluded: # excluded via string array
- id
- URL
- GlobalAPIKey
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)

